# Generated by Django 4.1.3 on 2022-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, unique=True, verbose_name="이름"),
        ),
    ]
