name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Set env vars
      run: echo "::set-env name=MY_SECRET_ENV_VAR::${{ secrets.MY_SECRET_ENV_VAR }}"
    - name: Run Migrations # run migrations to create table in side car db container
      run: pipenv run python manage.py migrate
    - name: Run Tests
      run: |
        pipenv run python manage.py test
